---
- name: Initialize and Unseal HashiCorp Vault
  hosts: localhost  # You can modify this to target specific hosts

  tasks:
    - name: Login to OpenShift
      shell: oc login --token={{ openshift_token }} --server={{ openshift_url }}:6443

    - name: Wait for pods to be running
      shell: oc get pods -n vault --no-headers | grep Running | wc -l
      register: pod_count
      until: pod_count.stdout|int >= 1
      retries: 12  # Adjust as needed
      delay: 10    # Adjust as needed

    - name: Initialize Vault
      shell: oc -n vault rsh hashicorp-vault-0 vault operator init
      register: vault_init_output

    - name: Extract unseal keys and root token
      set_fact:
        vault_unseal_keys: "{{ vault_init_output.stdout_lines | map('split', ': ') | selectattr('0', 'in', ['Unseal Key 1', 'Unseal Key 2', 'Unseal Key 3']) | map(attribute=1) | list }}"
        vault_root_token: "{{ vault_init_output.stdout_lines | select('match', '^Initial Root Token:') | map('split', ': ') | map(attribute=1) | list | first }}"

    - name: Display extracted values
      debug:
        var: item
      loop:
        - "{{ vault_unseal_keys }}"
        - "{{ vault_root_token }}"

    - name: Unseal Vault
      shell: "oc -n vault rsh hashicorp-vault-0 vault operator unseal {{ item }}"
      loop: "{{ vault_unseal_keys }}"

    - name: Join pods to Raft cluster and unseal them
      shell: |
        oc -n vault rsh {{ item }} vault operator raft join http://hashicorp-vault-0.vault-internal:8200
        oc -n vault rsh {{ item }} vault operator unseal {{ vault_unseal_keys[0] }}
        oc -n vault rsh {{ item }} vault operator unseal {{ vault_unseal_keys[1] }}
        oc -n vault rsh {{ item }} vault operator unseal {{ vault_unseal_keys[2] }}
      loop: "{{ ['hashicorp-vault-0'] }}"  # You can add more pods here

    - name: Login to Vault
      shell: "oc -n vault rsh hashicorp-vault-0 vault login {{ vault_root_token }}"
