---
- name: Deploy External Secrets Operator using Kustomize
  shell: |
    kustomize build {{ playbook_dir }}/openshift/apps/external-secrets-operator | oc apply -f -
  delegate_to: localhost
  become: false
  when: install_vault | bool
