---
# tasks file for configure-infra
- name: Configure offline token 
  import_tasks: openshift-login.yaml
  tags: always 

- name: Install  HashiCorp Vault helm
  import_tasks: deploy-vault.yml

- name: Initialize and Unseal HashiCorp Vault
  import_tasks: vault-init.yaml

- name: Deploy External Secrets Operator using Kustomize
  import_tasks: deploy-external-secrets-operator.yml
  when: install_vault | bool
