---
- name: Wait for pods to be running
  shell: oc get pods -n hashicorp-vault --no-headers | grep Running | wc -l
  register: pod_count
  until: pod_count.stdout|int >= 1
  retries: 10  # Adjust as needed
  delay: 30    # Adjust as needed
  environment:
    HELM_HOME: "{{ helm_home_env }}"
    HELM_CACHE_HOME: "{{ helm_cache_home }}"
  when: install_vault | bool

- name: Initialize Vault
  shell: oc -n hashicorp-vault rsh hashicorp-vault-0 vault operator init
  register: vault_init_output
  environment:
    HELM_HOME: "{{ helm_home_env }}"
    HELM_CACHE_HOME: "{{ helm_cache_home }}"
  when: install_vault | bool

- name: Extract unseal keys and root token
  set_fact:
    vault_unseal_keys: "{{ vault_init_output.stdout_lines | map('split', ': ') | selectattr('0', 'in', ['Unseal Key 1', 'Unseal Key 2', 'Unseal Key 3']) | map(attribute=1) | list }}"
    vault_root_token: "{{ vault_init_output.stdout_lines | select('match', '^Initial Root Token:') | map('split', ': ') | map(attribute=1) | list | first }}"
  when: install_vault | bool

- name: Display extracted values
  debug:
    var: item
  loop:
    - "{{ vault_unseal_keys }}"
    - "{{ vault_root_token }}"
  when: install_vault | bool

- name: Unseal Vault
  shell: "oc -n hashicorp-vault rsh hashicorp-vault-0 vault operator unseal {{ item }}"
  loop: "{{ vault_unseal_keys }}"
  environment:
    HELM_HOME: "{{ helm_home_env }}"
    HELM_CACHE_HOME: "{{ helm_cache_home }}"
  when: install_vault | bool

- name: Join pods to Raft cluster and unseal them
  shell: |
    oc -n hashicorp-vault rsh {{ item }} vault operator raft join http://hashicorp-vault-0.vault-internal:8200
    oc -n hashicorp-vault rsh {{ item }} vault operator unseal {{ vault_unseal_keys[0] }}
    oc -n hashicorp-vault rsh {{ item }} vault operator unseal {{ vault_unseal_keys[1] }}
    oc -n hashicorp-vault rsh {{ item }} vault operator unseal {{ vault_unseal_keys[2] }}
  loop: "{{ ['hashicorp-vault-0'] }}"  # You can add more pods here
  environment:
    HELM_HOME: "{{ helm_home_env }}"
    HELM_CACHE_HOME: "{{ helm_cache_home }}"
  when: install_vault | bool

- name: Login to Vault
  shell: "oc -n hashicorp-vault rsh hashicorp-vault-0 vault login {{ vault_root_token }}"
  environment:
    HELM_HOME: "{{ helm_home_env }}"
    HELM_CACHE_HOME: "{{ helm_cache_home }}"
  when: install_vault | bool

# Print out Root Token and prompt user to save it 
- name: Print out Root Token and prompt user to save it
  debug:
    msg: |
      Root Token: {{ vault_root_token }} \n
      Please save this token to a safe place. You will need it to access Vault.
  when: install_vault | bool