apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: deploy-vault-instance-pipeline-run-
spec:
  pipelineRef:
    name: deploy-vault-instance-pipeline
  params:
    - name: quay_username
      value: "your-quay-username"  # Replace with the actual value
    - name: image_tag
      value: "your-image-tag"  # Replace with the actual value
    - name: openshift_token
      value: "your-openshift-token"
    - name: openshift_url
      value: "https://your-openshift-url"
    - name: insecure_skip_tls_verify
      value: "true"
    - name: install_vault
      value: "true"
    - name: push_secrets
      value: "{{ params.install_vault == 'true' ? 'true' : 'false' }}"  # Automatically set push_secrets to false if install_vault is false
    - name: vault_secrets_init
      value: "false"
    - name: localClusterDomain
      value: "apps.foo.cluster.com"
    - name: hubClusterDomain
      value: "apps.hub.example.com"
    - name: clusterDomain
      value: "foo.example.com"
    - name: pattern_dir
      value: "/home/your-username/external-secrets-manager"
    - name: vault_helm
      value: "0.28.1"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-shared-workspace-pvc

