apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-vault-instance-pipeline
  namespace: hashicorp-vault
spec:
  params:
    - default: takinosh
      description: Quay username
      name: quay_username
      type: string
    - default: latest
      description: Image tag
      name: image_tag
      type: string
    - default: sha256~XXXXXXX-XXXXXXXX
      description: OpenShift token
      name: openshift_token
      type: string
    - default: 'https://api.ocp4.xxxx.example.com:6443'
      description: OpenShift URL
      name: openshift_url
      type: string
    - default: 'true'
      description: Skip TLS verification
      name: insecure_skip_tls_verify
      type: string
    - default: 'true'
      description: Install Vault
      name: install_vault
      type: string
    - default: 'false'
      description: Push secrets
      name: push_secrets
      type: string
    - default: 'false'
      description: Initialize Vault secrets
      name: vault_secrets_init
      type: string
    - default: apps.ocp4.xxxx.example.com
      description: Local cluster domain
      name: localClusterDomain
      type: string
    - default: apps.ocp4.xxxx.example.com
      description: Hub cluster domain
      name: hubClusterDomain
      type: string
    - default: ocp4.xxxx.example.com
      description: Cluster domain
      name: clusterDomain
      type: string
    - default: '{{ lookup(''env'', ''HOME'') }}/external-secrets-manager'
      description: Pattern directory
      name: pattern_dir
      type: string
    - default: 0.28.1
      description: Vault Helm chart version
      name: vault_helm
      type: string
  tasks:
    - name: git-clone-repo
      params:
        - name: url
          value: 'https://github.com/tosin2013/external-secrets-manager.git'
        - name: revision
          value: main
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: check-workspace-not-empty
      runAfter:
        - git-clone-repo
      taskSpec:
        metadata: {}
        spec: null
        steps:
          - computeResources: {}
            image: 'alpine:latest'
            name: check-workspace
            script: |
              #!/bin/sh
              if [ -z "$(ls -A /workspace/shared-workspace)" ]; then
                echo "Workspace is empty after git clone"
                exit 1
              else
                echo "Workspace is not empty"
                ls -la /workspace/shared-workspace
              fi
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: create-ansible-navigator-config
      params:
        - name: quay_username
          value: $(params.quay_username)
        - name: image_tag
          value: $(params.image_tag)
      runAfter:
        - check-workspace-not-empty
      taskSpec:
        metadata: {}
        params:
          - name: quay_username
            type: string
          - name: image_tag
            type: string
        spec: null
        steps:
          - computeResources: {}
            env:
              - name: QUAY_USERNAME
                value: $(params.quay_username)
              - name: IMAGE_TAG
                value: $(params.image_tag)
            image: 'quay.io/takinosh/external-secrets-manager@sha256:8db3fc2b01312bde4608db60287a0480200076183c449549affb2ff3dd2c11f9'
            name: create-config
            script: |
              #!/bin/sh
              ls -lath /workspace/shared-workspace
              ls -R /workspace/shared-workspace
              cat > /workspace/shared-workspace/.ansible-navigator.yml <<EOF
              ---
              ansible-navigator:
                ansible:
                  inventory:
                    entries:
                    - /workspace/shared-workspace/inventories/bastion
                  roles_path: /workspace/shared-workspace/roles
              ---
              ansible-navigator:
                ansible:
                  inventory:
                    entries:
                    - /workspace/shared-workspace/inventories/bastion
                execution-environment:
                  container-engine: podman
                  enabled: true
                  environment-variables:
                    pass:
                    - USER
                  image: quay.io/${QUAY_USERNAME}/external-secrets-manager:${IMAGE_TAG}
                  pull:
                    policy: missing
                logging:
                  append: true
                  file: /tmp/navigator/ansible-navigator.log
                  level: debug
                playbook-artifact:
                  enable: false
              EOF
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: update-inventory-file
      params:
        - name: openshift_token
          value: $(params.openshift_token)
        - name: openshift_url
          value: $(params.openshift_url)
        - name: insecure_skip_tls_verify
          value: $(params.insecure_skip_tls_verify)
        - name: install_vault
          value: $(params.install_vault)
        - name: push_secrets
          value: $(params.push_secrets)
        - name: vault_secrets_init
          value: $(params.vault_secrets_init)
        - name: localClusterDomain
          value: $(params.localClusterDomain)
        - name: hubClusterDomain
          value: $(params.hubClusterDomain)
        - name: clusterDomain
          value: $(params.clusterDomain)
        - name: pattern_dir
          value: $(params.pattern_dir)
        - name: image_tag
          value: $(params.image_tag)
        - name: vault_helm
          value: $(params.vault_helm)
      runAfter:
        - create-ansible-navigator-config
      taskSpec:
        metadata: {}
        params:
          - name: openshift_token
            type: string
          - name: openshift_url
            type: string
          - name: insecure_skip_tls_verify
            type: string
          - name: install_vault
            type: string
          - name: push_secrets
            type: string
          - name: vault_secrets_init
            type: string
          - name: localClusterDomain
            type: string
          - name: hubClusterDomain
            type: string
          - name: clusterDomain
            type: string
          - name: pattern_dir
            type: string
          - name: image_tag
            type: string
          - name: vault_helm
            type: string
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/takinosh/external-secrets-manager@sha256:8db3fc2b01312bde4608db60287a0480200076183c449549affb2ff3dd2c11f9'
            name: update-inventory
            script: |
              #!/bin/sh
              mkdir -p /workspace/shared-workspace/inventories/bastion
              echo "[control]" > /workspace/shared-workspace/inventories/bastion/hosts
              echo "roles_path=/workspace/shared-workspace/roles" >> /workspace/shared-workspace/inventories/bastion/hosts
              echo "control ansible_host=localhost ansible_user=runner" >> /workspace/shared-workspace/inventories/bastion/hosts
              cat > /workspace/shared-workspace/inventories/controller/group_vars/all.yml <<EOF
              openshift_token: $(params.openshift_token)
              openshift_url: $(params.openshift_url)
              insecure_skip_tls_verify: $(params.insecure_skip_tls_verify)

              install_vault: $(params.install_vault)
              push_secrets: $(params.push_secrets)
              vault_secrets_init: $(params.vault_secrets_init)

              localClusterDomain: $(params.localClusterDomain)
              hubClusterDomain: $(params.hubClusterDomain)
              clusterDomain: $(params.clusterDomain)

              pattern_dir: $(params.pattern_dir)

              image_tag: $(params.image_tag)
              vault_helm: $(params.vault_helm)
              vault_helm_version: v$(params.vault_helm)
              vault_helm_route_tag: vault-$(params.vault_helm)
              EOF
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: deploy-configure-vault
      params:
        - name: openshift_token
          value: $(params.openshift_token)
        - name: openshift_url
          value: $(params.openshift_url)
        - name: insecure_skip_tls_verify
          value: $(params.insecure_skip_tls_verify)
        - name: install_vault
          value: $(params.install_vault)
        - name: pattern_dir
          value: $(params.pattern_dir)
        - name: image_tag
          value: $(params.image_tag)
      runAfter:
        - update-inventory-file
      taskSpec:
        metadata: {}
        params:
          - name: openshift_token
            type: string
          - name: openshift_url
            type: string
          - name: insecure_skip_tls_verify
            type: string
          - name: install_vault
            type: string
          - name: pattern_dir
            type: string
          - name: image_tag
            type: string
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/takinosh/external-secrets-manager@sha256:8db3fc2b01312bde4608db60287a0480200076183c449549affb2ff3dd2c11f9'
            name: deploy-vault
            script: |
              #!/bin/sh
              ansible-playbook /workspace/shared-workspace/install-vault.yaml --extra-vars "install_vault=$(params.install_vault)" --extra-vars "openshift_token=$(params.openshift_token)" --extra-vars "openshift_url=$(params.openshift_url)" --extra-vars "insecure_skip_tls_verify=$(params.insecure_skip_tls_verify)" --extra-vars "pattern_dir=$(params.pattern_dir)" --extra-vars "image_tag=$(params.image_tag)" --vault-password-file /root/.vault_password
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
    - name: push-secrets
      params:
        - name: vault_secrets_init
          value: $(params.vault_secrets_init)
        - name: push_secrets
          value: $(params.push_secrets)
        - name: openshift_token
          value: $(params.openshift_token)
        - name: openshift_url
          value: $(params.openshift_url)
        - name: insecure_skip_tls_verify
          value: $(params.insecure_skip_tls_verify)
        - name: pattern_dir
          value: $(params.pattern_dir)
        - name: image_tag
          value: $(params.image_tag)
      runAfter:
        - deploy-configure-vault
      taskSpec:
        metadata: {}
        params:
          - name: vault_secrets_init
            type: string
          - name: push_secrets
            type: string
          - name: openshift_token
            type: string
          - name: openshift_url
            type: string
          - name: insecure_skip_tls_verify
            type: string
          - name: pattern_dir
            type: string
          - name: image_tag
            type: string
        spec: null
        steps:
          - computeResources: {}
            image: 'quay.io/takinosh/external-secrets-manager@sha256:8db3fc2b01312bde4608db60287a0480200076183c449549affb2ff3dd2c11f9'
            name: push-secrets
            script: |
              #!/bin/sh
              ansible-playbook /workspace/shared-workspace/push-secrets.yaml --extra-vars "vault_push_secrets=$(params.push_secrets)" --extra-vars "vault_secrets_init=$(params.vault_secrets_init)" --extra-vars "openshift_token=$(params.openshift_token)" --extra-vars "openshift_url=$(params.openshift_url)" --extra-vars "insecure_skip_tls_verify=$(params.insecure_skip_tls_verify)" --extra-vars "pattern_dir=$(params.pattern_dir)" --extra-vars "image_tag=$(params.image_tag)" --vault-password-file /root/.vault_password
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
