apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-routes
  namespace: hashicorp-vault
subjects:
- kind: ServiceAccount
  name: workspace8c5a59f24c654f27-sa
  namespace: admin-devspaces
roleRef:
  kind: Role
  name: route-manager
  apiGroup: rbac.authorization.k8s.io
